baseURL = "https://math.iisc.ac.in/~gadgil/proofs-and-programs-2025/"
languageCode = "en-us"
title = "MA 208: Proofs and Programs"
theme = "course"
buildFuture = "true"
[params]
    code = "MA 208"
    course = "Proofs and Programs"
    term = "January 2025"
[markup.goldmark.renderer]
unsafe= true